In [22]:
#1

import numpy as np
students_gpas = np.array(
    [
        [4.0, 3.286, 3.5, 4.0],
        [3.2, 3.8, 4.0, 4.0],
        [3.96, 3.92, 4.0, 4.0]
    ], 
    np.float16)

students_gpas

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

In [24]:
#2

students_gpas.shape

(3, 4)

In [25]:
#3

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
#4

row_r1 = a[1, :] 
print(row_r1)

[5 6 7 8]


In [27]:
#5

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
lt = a[2, 1:]
lt[::-1]

array([12, 11, 10])

In [33]:
#6

f = open('C:/Users/HP LAPTOP/Documents/งาน flutter/Final_Exam/file.txt')
f.read()

'This is 1st line\nThis is 2nd line\nThis is 3rd line\nThis is 4th line\nThis is 5th line'

In [34]:
data = ["This is 1st line",
        "This is 2nd line",
        "This is 3rd line",
        "This is 4th line",
        "This is 5th line"]

with open('C:/Users/HP LAPTOP/Documents/งาน flutter/Final_Exam/file.txt', 'w') as fp:
    for line in data:
        fp.write(line+"\n")
        
with open('C:/Users/HP LAPTOP/Documents/งาน flutter/Final_Exam/file.txt', 'r') as fp:  
    line = fp.readline()
    while line:
        print("{}".format(line.strip()))
        line = fp.readline()

This is 1st line
This is 2nd line
This is 3rd line
This is 4th line
This is 5th line


In [68]:
#7

f = open('C:/Users/HP LAPTOP/Documents/งาน flutter/Final_Exam/data.csv')
f.read()

'myData = [,\n,"[""first_name"", ""second_name"", ""Grade""],"\n,"[\'Alex\', \'Brian\', \'A\'],"\n,"[\'Tom\', \'Smith\', \'B\']"\n],\n'

In [69]:
with open('C:/Users/HP LAPTOP/Documents/งาน flutter/Final_Exam/data.csv') as fp:  
    cnt = 1
    for line in fp:
        print(" {}: {}".format(cnt, line.strip()))
        cnt += 1

 1: myData = [,
 2: ,"[""first_name"", ""second_name"", ""Grade""],"
 3: ,"['Alex', 'Brian', 'A'],"
 4: ,"['Tom', 'Smith', 'B']"
 5: ],


In [72]:
#8

import pandas as pd
persons = {
    "ชื่อ": ["พิศาล", "ปรเมษฐ", "สมชาย"],
    "สกุล": ["สุขขี", "สุขะตะ", "รักดี"],
    "โทร": ["0842982456", "0889152456", "0886123546"]
}

data = pd.DataFrame(persons)
data.head()

ชื่อ    สกุล         โทร
0   พิศาล   สุขขี  0842982456
1  ปรเมษฐ  สุขะตะ  0889152456
2   สมชาย   รักดี  0886123546

In [73]:
#9

data[["โทร"]]

โทร
0  0842982456
1  0889152456
2  0886123546

In [77]:
#10

tel = data[data["ชื่อ"]=='พิศาล']
print(tel)

    ชื่อ   สกุล         โทร
0  พิศาล  สุขขี  0842982456
